# https://alacritty.org/config-alacritty.html

# https://toml.io/en/v1.0.0

[window]
padding = { x = 5, y = 3 }
dynamic_padding = true
opacity = 0.1

# Font configuration
[font]
size = 11.0
#normal = { family = "FreeSerif", style = "Regular" }
#normal = { family = "monospace", style = "Regular" }
#normal = { family = "FiraCode Nerd Font", style = "Regular" }

# Cursor settings
[cursor]
style = { shape = "Block", blinking = "On" }

# Scrollback buffer (number of lines stored)
#scrolling.history = 10000

# Color scheme
#colors.primary.background = "#282828"
#colors.primary.foreground = "#ebdbb2"
#
#colors.normal.black = "#282828"
#colors.normal.red = "#cc241d"
#colors.normal.green = "#98971a"
#colors.normal.yellow = "#d79921"
#colors.normal.blue = "#458588"
#colors.normal.magenta = "#b16286"
#colors.normal.cyan = "#689d6a"
#colors.normal.white = "#a89984"
#
#colors.bright.black = "#928374"
#colors.bright.red = "#fb4934"
#colors.bright.green = "#b8bb26"
#colors.bright.yellow = "#fabd2f"
#colors.bright.blue = "#83a598"
#colors.bright.magenta = "#d3869b"
#colors.bright.cyan = "#8ec07c"
#colors.bright.white = "#ebdbb2"

# Keybindings (example: Ctrl+Shift+V for paste)
#keyboard.bindings = [
#    { key = "V", mods = "Control|Shift", action = "Paste" },
#    { key = "C", mods = "Control|Shift", action = "Copy" },
#    { key = "K", mods = "Control", action = "ScrollPageUp" },
#    { key = "J", mods = "Control", action = "ScrollPageDown" }
#]

